/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;
import newpackage.*;

/**
 *
 * @author admin
 */
public class PanelCover extends javax.swing.JPanel {

    private final DecimalFormat df = new DecimalFormat("##0.###");
    private ActionListener event;
    private MigLayout layout;
    private JLabel title;
    private JLabel de;
    private JLabel de2;
    private ButtonOutLine button;
    private boolean isLogin;

    public PanelCover() {
        initComponents();
    }

    public void addEvent(ActionListener event) {
        this.event = event;
        layout = new MigLayout("wrap, fill", "[center]", "push[]25[]15[]15[]push");
        setLayout(layout);
        init();

    }

    private void init() {
        title = new JLabel("Chào mừng !");
        title.setFont(new Font("sansserif", 1, 40));
        title.setForeground(new Color(245, 245, 245));
        add(title);
        de = new JLabel("Để sử dụng phần mềm C&T vui lòng");
        de.setFont(new Font("sansserif", 1, 16));
        de.setForeground(new Color(245, 245, 245));
        add(de);
        de2 = new JLabel("nhập Username và Password của bạn!");
        de2.setFont(new Font("sansserif", 1, 16));

        de2.setForeground(new Color(245, 245, 245));
        add(de2);
        button = new ButtonOutLine();
        button.setBackground(new Color(255, 255, 255));
        button.setForeground(new Color(255, 255, 255));
        button.setFont(new Font("sansserif", 1, 12));
        button.setText("QUÊN MẬT KHẨU");

        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.actionPerformed(e);
            }
        });
        add(button, "w 60%, h 40");

    }

    public void resignLeft(double v) {
        v = Double.valueOf(df.format(v).toString().replace(",", "."));
        login(false);
        layout.setComponentConstraints(title, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(de, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(de2, "pad 0 -" + v + "% 0 0");
    }

    public void resignRight(double v) {
        v = Double.valueOf(df.format(v).toString().replace(",", "."));
        login(false);
        layout.setComponentConstraints(title, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(de, "pad 0 -" + v + "% 0 0");
        layout.setComponentConstraints(de2, "pad 0 -" + v + "% 0 0");

    }

    public void loginLeft(double v) {
        v = Double.valueOf(df.format(v).toString().replace(",", "."));
        login(true);
        layout.setComponentConstraints(title, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(de, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(de2, "pad 0 " + v + "% 0 " + v + "%");

    }

    public void loginRight(double v) {
        v = Double.valueOf(df.format(v).toString().replace(",", "."));
        login(true);
        layout.setComponentConstraints(title, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(de, "pad 0 " + v + "% 0 " + v + "%");
        layout.setComponentConstraints(de2, "pad 0 " + v + "% 0 " + v + "%");

    }

    public void login(boolean login) {
        if (this.isLogin != login) {
            if (login) {
                title.setText("Xin chào !");
                de.setText("Bạn quên mất mật khẩu, nhập Username");
                de2.setText("của bạn để lấy lại mật khẩu !");
                button.setText("ĐĂNG NHẬP");
            } else {
                title.setText("Chào mừng !");
                de.setText("Để sử dụng phần mềm C&T vui lòng");
                de2.setText("nhập Username và Password của bạn!");
                button.setText("QUÊN MẬT KHẨU");
            }
            this.isLogin = login;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(81, 145, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
